
function esc(t){ if(t===null||t===undefined) return ''; return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
const _shopFromUrl = new URLSearchParams(window.location.search).get('shop');
if(_shopFromUrl){ localStorage.setItem('vendeur_shop', _shopFromUrl); localStorage.setItem('vendeur_shop_locked', _shopFromUrl); }
const _lockedShop = localStorage.getItem('vendeur_shop_locked');
const firebaseConfig={apiKey:"AIzaSyBOD42Ibg7tGVafz44cwCyI0CUjgAn5MNY",authDomain:"bateke-v4.firebaseapp.com",databaseURL:"https://bateke-v4-default-rtdb.firebaseio.com",projectId:"bateke-v4",storageBucket:"bateke-v4.firebasestorage.app",messagingSenderId:"321333206282",appId:"1:321333206282:web:6d1603446be3d195de6ef3"};
firebase.initializeApp(firebaseConfig);
const db=firebase.database();
let AUTH_READY=false;
firebase.auth().signInAnonymously().then(()=>{AUTH_READY=true; document.getElementById('authStatus').innerText='✅ Connecté';}).catch(e=>{document.getElementById('authStatus').innerText='❌ '+e.message;});
let SHOP=localStorage.getItem('vendeur_shop')||'Menkao1';
if(_lockedShop) SHOP=_lockedShop;
let STOCK=[],VENTES=[],DEP=[],VERS=[];let PANIER=[];let CURRENT_VENDEUR=null;let SHOPS_LIST=JSON.parse(localStorage.getItem('bateke_shops_list')||'["Menkao1","Menkao2","Mbakana"]');
let CONFIG_ENT={nom:'ETS BATEKE',adresse:'Kinshasa',rccm:'',tva:16,devise:'FC',deviseBase:'FC',taux:{USD:0,EUR:0,XAF:0,XOF:0},tauxUSD:0,tauxEUR:0,logo:'',piedFacture:'',piedDevis:'',tel:'',email:'',idnat:''};
let PANIER_DEVIS=[],PANIER_FACT=[],DEVIS=[],FACTURES=[];
let TEMP_OLD_PIN=null;let TEMP_OLD_DATA=null;let PRESENCE_REF=null;let HEARTBEAT_TIMER=null;
const CACHE_TTL = 12*3600000;
let IS_ONLINE = navigator.onLine;
let FIREBASE_CONNECTED = false;
let OFFLINE_QUEUE = JSON.parse(localStorage.getItem('bateke_queue_'+SHOP)||'[]');
let OFFLINE_STOCK_CACHE = JSON.parse(localStorage.getItem('bateke_stock_'+SHOP)||'[]');
let BLOCKED_PINS_CACHE = JSON.parse(localStorage.getItem('bateke_blocked_'+SHOP)||'[]');
function saveQueue(){ localStorage.setItem('bateke_queue_'+SHOP, JSON.stringify(OFFLINE_QUEUE)); updateOfflineUI(); }
function saveStockCache(){ localStorage.setItem('bateke_stock_'+SHOP, JSON.stringify(STOCK)); }
function saveBlockedCache(){ localStorage.setItem('bateke_blocked_'+SHOP, JSON.stringify(BLOCKED_PINS_CACHE)); }
function saveShopsCache(list){ localStorage.setItem('bateke_shops_list', JSON.stringify(list)); }
function isCacheExpired(){ let lastAuth = parseInt(localStorage.getItem('bateke_last_auth_'+SHOP)||'0'); if(!lastAuth) return false; return (Date.now()-lastAuth) > CACHE_TTL; }
function updateLastAuth(){ localStorage.setItem('bateke_last_auth_'+SHOP, Date.now().toString()); }
function updateOfflineUI(){
 let badge=document.getElementById('offlineBadge'); let qInfo=document.getElementById('queueInfo'); let btn=document.getElementById('btnSync');
 let q=OFFLINE_QUEUE.length;
 let expMsg = isCacheExpired()? ' | ⚠️ CACHE EXPIRE - Internet requis' : ' | Cache 12h OK';
 if(qInfo) qInfo.innerText = q? `🔴 OFFLINE - ${q} en attente${expMsg}` : `🟢 SYNC OK - ${STOCK.length} articles${expMsg}`;
 if(badge){
  if(isCacheExpired()){ badge.style.background='#000'; badge.style.color='#fff'; badge.innerText='⚠️ CACHE EXPIRE'; }
  else if(!IS_ONLINE ||!FIREBASE_CONNECTED){ badge.style.background='#ef4444'; badge.style.color='#fff'; badge.innerText = q? `🔴 OFFLINE ${q}` : '🔴 HORS LIGNE'; }
  else if(q>0){ badge.style.background='#facc15'; badge.style.color='#000'; badge.innerText = `🟡 SYNC ${q}...`; }
  else { badge.style.background='#22c55e'; badge.style.color='#000'; badge.innerText = '🟢 SYNC OK'; }
 }
 if(btn){ btn.style.display = q>0? 'block' : 'none'; }
 document.getElementById('stockSource').innerText = (!IS_ONLINE ||!FIREBASE_CONNECTED)? 'LOCAL OFFLINE' : 'SERVEUR';
}
db.ref('.info/connected').on('value',snap=>{ FIREBASE_CONNECTED = snap.val()===true; updateOfflineUI(); if(FIREBASE_CONNECTED) syncOfflineQueue(); });
window.addEventListener('online',()=>{ IS_ONLINE=true; updateOfflineUI(); syncOfflineQueue(); setPresenceOnline(); });
window.addEventListener('offline',()=>{ IS_ONLINE=false; FIREBASE_CONNECTED=false; updateOfflineUI(); });
async function syncOfflineQueue(){
 if(!IS_ONLINE ||!FIREBASE_CONNECTED) return; if(!OFFLINE_QUEUE.length) return;
 if(CURRENT_VENDEUR){ try{ let snap=await db.ref('shops/'+SHOP+'/vendeurs/'+CURRENT_VENDEUR.pin).once('value'); if(!snap.val() || snap.val().actif===false){ alert('🚫 Compte bloqué - sync annulée, déconnexion'); OFFLINE_QUEUE=[]; saveQueue(); logoutAll(); return; } }catch(e){} }
 let remaining=[]; for(let item of OFFLINE_QUEUE){ try{
   if(item.type==='vente'){ let vendSnap=await db.ref('shops/'+item.shop+'/vendeurs/'+(item.data.vendeurPin||'')).once('value'); if(!vendSnap.val() || vendSnap.val().actif===false) continue; await db.ref('shops/'+item.shop+'/ventes/'+item.id).set(item.data); if(item.stockUpdates){ for(let u of item.stockUpdates){ await db.ref('shops/'+item.shop+'/stock/'+u.CODE).update({Quantite:u.newQte}); } } }
   else if(item.type==='depense'){ await db.ref('shops/'+item.shop+'/depenses/'+item.id).set(item.data); }
   else if(item.type==='versement'){ await db.ref('shops/'+item.shop+'/versements/'+item.id).set(item.data); }
   else if(item.type==='entree'){ await db.ref('shops/'+item.shop+'/stock/'+item.CODE).update({Quantite:item.newQte}); await db.ref('shops/'+item.shop+'/entrees/'+item.id).set(item.data); }
  } catch(e){ remaining.push(item); } } OFFLINE_QUEUE=remaining; saveQueue(); updateOfflineUI();
}
setInterval(syncOfflineQueue, 15000);
document.getElementById('loginShopName').innerText='Boutique: '+SHOP;
document.getElementById('shopName').innerText=SHOP;
document.getElementById('shopStock').innerText=SHOP;
if(_lockedShop){ const _sel=document.getElementById('shopSel'); if(_sel){ _sel.disabled=true; _sel.style.opacity='0.6'; _sel.style.background='#ccc'; } }
document.getElementById('du').valueAsDate=new Date(new Date().setDate(1));document.getElementById('au').valueAsDate=new Date();
db.ref('shops').on('value',snap=>{
 let data=snap.val()||{}; let list=Object.keys(data); if(!list.length) list=['Menkao1','Menkao2','Mbakana'];
 SHOPS_LIST=list; saveShopsCache(list);
 if(!_lockedShop){ let opts=list.map(s=>`<option ${s===SHOP?'selected':''} value="${s}">${s}</option>`).join(''); document.getElementById('shopSel').innerHTML=opts; } else { document.getElementById('shopSel').innerHTML=`<option selected>${_lockedShop}</option>`; }
 document.getElementById('loginShopName').innerText='Boutique: '+SHOP+(isCacheExpired()?' ⚠️ EXPIRE':'');
 if(data[SHOP] && data[SHOP].vendeurs){ let blocked=Object.entries(data[SHOP].vendeurs).filter(([k,v])=>v.actif===false).map(([k])=>k); BLOCKED_PINS_CACHE=blocked; saveBlockedCache(); }
});
if(!navigator.onLine){ OFFLINE_STOCK_CACHE = JSON.parse(localStorage.getItem('bateke_stock_'+SHOP)||'[]'); if(OFFLINE_STOCK_CACHE.length){ STOCK=OFFLINE_STOCK_CACHE; } AUTH_READY=true; document.getElementById('authStatus').innerText='🔴 MODE OFFLINE - Cache local 12h'; updateOfflineUI(); }
function setPresenceOnline(){ if(!CURRENT_VENDEUR ||!CURRENT_VENDEUR.pin) return; if(!IS_ONLINE ||!FIREBASE_CONNECTED) return; let pin=CURRENT_VENDEUR.pin; let nom=CURRENT_VENDEUR.nom||pin; let ref=db.ref('shops/'+SHOP+'/presence/'+pin); PRESENCE_REF=ref; ref.set({online:true,lastSeen:Date.now(),nom:nom,pin:pin,shop:SHOP}); ref.onDisconnect().set({online:false,lastSeen:Date.now(),nom:nom,pin:pin,shop:SHOP}); if(HEARTBEAT_TIMER) clearInterval(HEARTBEAT_TIMER); HEARTBEAT_TIMER=setInterval(()=>{ if(IS_ONLINE) ref.update({lastSeen:Date.now(),online:true}); },60000); logPresence('LOGIN'); cleanupOldLogs(); }
function setPresenceOffline(){ try{ if(PRESENCE_REF){ PRESENCE_REF.update({online:false,lastSeen:Date.now()}); PRESENCE_REF.onDisconnect().cancel(); } else if(CURRENT_VENDEUR && CURRENT_VENDEUR.pin){ db.ref('shops/'+SHOP+'/presence/'+CURRENT_VENDEUR.pin).update({online:false,lastSeen:Date.now()}); } }catch(e){} if(HEARTBEAT_TIMER){ clearInterval(HEARTBEAT_TIMER); HEARTBEAT_TIMER=null; } logPresence('LOGOUT'); }
function logPresence(type, extra){ if(!CURRENT_VENDEUR ||!CURRENT_VENDEUR.pin) return; if(!FIREBASE_CONNECTED) return; let pin=CURRENT_VENDEUR.pin; let payload={ts:Date.now(),type:type,date:new Date().toISOString(),vendeur:CURRENT_VENDEUR.nom||pin,pin:pin,shop:SHOP}; if(extra) payload.extra=extra; db.ref('shops/'+SHOP+'/vendeur_logs/'+pin).push(payload); }
function cleanupOldLogs(){ if(!CURRENT_VENDEUR ||!CURRENT_VENDEUR.pin) return; if(!FIREBASE_CONNECTED) return; let pin=CURRENT_VENDEUR.pin; db.ref('shops/'+SHOP+'/vendeur_logs/'+pin).once('value').then(snap=>{ let vals=snap.val()||{}; let cutoff=Date.now()-7*24*3600000; Object.entries(vals).forEach(([k,v])=>{ if(v.ts && v.ts<cutoff) db.ref('shops/'+SHOP+'/vendeur_logs/'+pin+'/'+k).remove(); }); }); }
window.addEventListener('beforeunload',()=>{ setPresenceOffline(); });
async function doLogin(){
 let pin=(document.getElementById('pinInput').value||'').toString().trim();
 if(!pin){ document.getElementById('loginMsg').innerText='Entre ton PIN'; return; }
 if(BLOCKED_PINS_CACHE.includes(pin)){ document.getElementById('loginMsg').innerText='🚫 PIN BLOQUÉ (blacklist)'; return; }
 if(!navigator.onLine && isCacheExpired()){ document.getElementById('loginMsg').innerText='⚠️ Cache expiré (12h). Connecte internet pour reverifier'; return; }
 if(!AUTH_READY && navigator.onLine){ document.getElementById('loginMsg').innerText='Attends 2 sec...'; setTimeout(doLogin,1000); return; }
 document.getElementById('loginMsg').innerText='Vérification...';
 if(pin==='9999'){ CURRENT_VENDEUR={nom:'PATRON', pin:'9999', role:'patron'}; localStorage.setItem('vendeur_pin',pin); localStorage.setItem('vendeur_nom','PATRON'); document.getElementById('loginOverlay').style.display='none'; document.getElementById('vendeurName').innerText='PATRON'; updateLastAuth(); setPresenceOnline(); listenAll(); return; }
 try{
   if(!FIREBASE_CONNECTED){ let cachedVendeurs=JSON.parse(localStorage.getItem('bateke_vendeurs_'+SHOP)||'{}'); let vend=cachedVendeurs[pin]; if(vend && vend.actif!==false){ CURRENT_VENDEUR=vend; document.getElementById('loginOverlay').style.display='none'; document.getElementById('vendeurName').innerText=vend.nom||pin; listenAll(); return; } else { document.getElementById('loginMsg').innerText='🔴 OFFLINE: PIN non en cache ou bloqué'; return; } }
   let snap=await db.ref('shops/'+SHOP+'/vendeurs/'+pin).once('value'); let vend=snap.val(); if(!vend){ document.getElementById('loginMsg').innerText='PIN inconnu'; return; } if(vend.actif===false){ BLOCKED_PINS_CACHE.push(pin); saveBlockedCache(); document.getElementById('loginMsg').innerText='🚫 ACCÈS RÉVOQUÉ'; return; } let snapB=await db.ref('shops/'+SHOP+'/config/blocked').once('value'); if(snapB.val()===true){ document.getElementById('loginMsg').innerText='🚫 Boutique bloquée'; return; } if(vend.mustChangePin!==false){ TEMP_OLD_PIN=pin; TEMP_OLD_DATA=vend; CURRENT_VENDEUR=vend; document.getElementById('oldPinDisplay').innerText=pin; document.getElementById('changePinOverlay').style.display='flex'; document.getElementById('loginMsg').innerText=''; return; } CURRENT_VENDEUR=vend; localStorage.setItem('vendeur_pin',pin); localStorage.setItem('vendeur_nom',vend.nom||pin); let cacheV=JSON.parse(localStorage.getItem('bateke_vendeurs_'+SHOP)||'{}'); cacheV[pin]=vend; localStorage.setItem('bateke_vendeurs_'+SHOP, JSON.stringify(cacheV)); updateLastAuth(); document.getElementById('loginOverlay').style.display='none'; document.getElementById('vendeurName').innerText=vend.nom||pin; db.ref('shops/'+SHOP+'/vendeurs/'+pin).update({lastLogin:Date.now()}); setPresenceOnline(); listenAll(); }catch(e){ document.getElementById('loginMsg').innerText='Erreur: '+e.message; }
}
async function doChangePinForce(){
 let n1=(document.getElementById('newPin1').value||'').trim(); let n2=(document.getElementById('newPin2').value||'').trim(); let msg=document.getElementById('changePinMsg');
 if(n1.length<4){ msg.innerText='PIN trop court'; return; } if(n1!==n2){ msg.innerText='Ne correspond pas'; return; } if(n1===TEMP_OLD_PIN){ msg.innerText='Différent du temporaire'; return; }
 let snap=await db.ref('shops/'+SHOP+'/vendeurs/'+n1).once('value'); if(snap.exists()){ msg.innerText='Ce PIN existe déjà'; return; }
 let oldData=TEMP_OLD_DATA||CURRENT_VENDEUR; let newData={...oldData, pin:n1, mustChangePin:false, lastPinChange:Date.now(), oldTempPin:TEMP_OLD_PIN};
 msg.innerText='Migration...'; await db.ref('shops/'+SHOP+'/vendeurs/'+n1).set(newData); await db.ref('shops/'+SHOP+'/vendeurs/'+TEMP_OLD_PIN).remove();
 await db.ref('shops/'+SHOP+'/superLogs').push({ts:Date.now(), action:'VENDEUR_CHANGE_PIN', detail: oldData.nom+' '+TEMP_OLD_PIN+' -> '+n1, role:'VENDEUR', shop:SHOP});
 CURRENT_VENDEUR=newData; localStorage.setItem('vendeur_pin',n1); localStorage.setItem('vendeur_nom',newData.nom||n1);
 document.getElementById('changePinOverlay').style.display='none'; document.getElementById('loginOverlay').style.display='none'; document.getElementById('vendeurName').innerText=newData.nom||n1; document.getElementById('pinInput').value=n1; updateLastAuth(); alert('✅ Nouveau PIN: '+n1); setPresenceOnline(); listenAll();
}
function logoutAll(){ setPresenceOffline(); localStorage.removeItem('vendeur_shop'); localStorage.removeItem('vendeur_shop_locked'); localStorage.removeItem('vendeur_pin'); localStorage.removeItem('vendeur_nom'); location.href=location.pathname; }
function switchShop(){ if(_lockedShop){ document.getElementById('shopSel').value=_lockedShop; return; } SHOP=document.getElementById('shopSel').value;localStorage.setItem('vendeur_shop',SHOP);document.getElementById('shopName').innerText=SHOP;document.getElementById('shopStock').innerText=SHOP;document.getElementById('loginShopName').innerText='Boutique: '+SHOP; OFFLINE_QUEUE=JSON.parse(localStorage.getItem('bateke_queue_'+SHOP)||'[]'); OFFLINE_STOCK_CACHE=JSON.parse(localStorage.getItem('bateke_stock_'+SHOP)||'[]'); document.getElementById('loginOverlay').style.display='flex'; updateOfflineUI(); }
function switchTab(id){document.querySelectorAll('.sec').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));document.getElementById('btn-'+id).classList.add('active');}
function listenAll(){
 db.ref('shops/'+SHOP+'/config/blocked').on('value',snap=>{ if(snap.val()===true && (!CURRENT_VENDEUR || CURRENT_VENDEUR.pin!=='9999')){ document.getElementById('loginOverlay').style.display='flex'; document.getElementById('loginMsg').innerText='🚫 Boutique bloquée'; } });
 if(CURRENT_VENDEUR && CURRENT_VENDEUR.pin!=='9999'){ db.ref('shops/'+SHOP+'/vendeurs/'+CURRENT_VENDEUR.pin+'/actif').on('value',snap=>{ if(snap.val()===false){ BLOCKED_PINS_CACHE.push(CURRENT_VENDEUR.pin); saveBlockedCache(); alert('🚫 Accès révoqué'); logoutAll(); } }); db.ref('shops/'+SHOP+'/vendeurs').on('value',snap=>{ let vals=snap.val()||{}; let blocked=Object.entries(vals).filter(([k,v])=>v.actif===false).map(([k])=>k); BLOCKED_PINS_CACHE=blocked; saveBlockedCache(); }); }
 db.ref('shops/'+SHOP+'/stock').on('value',s=>{ if(s.val()){ STOCK=Object.values(s.val()); saveStockCache(); renderStock(); } else if(OFFLINE_STOCK_CACHE.length){ STOCK=OFFLINE_STOCK_CACHE; renderStock(); } });
 db.ref('shops/'+SHOP+'/ventes').on('value',s=>{VENTES=Object.values(s.val()||{});renderVentesJour();updateKPI();});
 db.ref('shops/'+SHOP+'/depenses').on('value',s=>{DEP=Object.values(s.val()||{});renderCaisse();updateKPI();});
 db.ref('shops/'+SHOP+'/versements').on('value',s=>{VERS=Object.values(s.val()||{});renderCaisse();updateKPI();});
 db.ref('shops/'+SHOP+'/config_entreprise').on('value',snap=>{CONFIG_ENT=Object.assign(CONFIG_ENT,snap.val()||{});let info=(CONFIG_ENT.nom||'ETS BATEKE')+' - Base: '+(CONFIG_ENT.deviseBase||'FC')+' - Taux USD:'+(CONFIG_ENT.taux?.USD||CONFIG_ENT.tauxUSD||'à définir');let el1=document.getElementById('devisConfigInfo');let el2=document.getElementById('factConfigInfo');if(el1)el1.innerText=info;if(el2)el2.innerText=info;autoFillTaux();});
 db.ref('shops/'+SHOP+'/devis').on('value',s=>{let v=s.val()||{};DEVIS=Object.entries(v).map(([k,x])=>({...x,_id:k})).sort((a,b)=>new Date(b.date)-new Date(a.date));renderDevisList();let sel=document.getElementById('selectDevisFact');if(sel)sel.innerHTML='<option value="">-- Choisir devis --</option>'+DEVIS.map(d=>`<option value="${d._id}">${d.numero} - ${d.client?.nom}</option>`).join('');});
 db.ref('shops/'+SHOP+'/factures').on('value',s=>{let v=s.val()||{};FACTURES=Object.entries(v).map(([k,x])=>({...x,_id:k})).sort((a,b)=>new Date(b.date)-new Date(a.date));renderFactList();});
 if(!FIREBASE_CONNECTED && OFFLINE_STOCK_CACHE.length){ STOCK=OFFLINE_STOCK_CACHE; renderStock(); }
}
function checkRemise(){let r=parseFloat(document.getElementById('remise').value)||0;if(r>10){alert('Remise max 10%');document.getElementById('remise').value=10;r=10;}if(r<0){document.getElementById('remise').value=0;}}
function getTotals(){let brut=PANIER.reduce((s,i)=>s+i.qty*i.Prix,0);let remisePct=parseFloat(document.getElementById('remise').value)||0;let remiseVal=brut*remisePct/100;let final=brut-remiseVal;return {brut,remisePct,remiseVal,final};}
function searchArticle(){let q=document.getElementById('searchArt').value.toLowerCase().trim();let sug=document.getElementById('suggest');if(!q){sug.style.display='none';return;}let f=STOCK.filter(p=>p.actif!==false).filter(p=>(p.CODE||'').toLowerCase().includes(q)||(p.Designation||'').toLowerCase().includes(q)).slice(0,10);if(!f.length){sug.style.display='none';return;}sug.innerHTML=f.map(p=>`<div onclick="selectArt('${p.CODE}')"><b>${p.CODE}</b> - ${p.Designation} - ${p['Prix Unit']?.toLocaleString()} FC - Stock:${p.Quantite}</div>`).join('');sug.style.display='block';}
function selectArt(code){let p=STOCK.find(x=>x.CODE===code);if(!p)return;document.getElementById('codeArt').value=p.CODE;document.getElementById('pvArt').value=p['Prix Unit'];document.getElementById('searchArt').value=p.CODE+' '+p.Designation;document.getElementById('suggest').style.display='none';document.getElementById('qteArt').focus();}
function addPanier(){let code=document.getElementById('codeArt').value;if(!code)return alert('Choisis article');let p=STOCK.find(x=>x.CODE===code);if(!p)return;if(p.actif===false)return alert('Article désactivé');let qte=parseInt(document.getElementById('qteArt').value)||1;if(qte>p.Quantite)return alert('Stock insuffisant: '+p.Quantite);let exist=PANIER.find(x=>x.CODE===code);if(exist)exist.qty+=qte;else PANIER.push({CODE:p.CODE,Designation:p.Designation,Prix:p['Prix Unit'],PA:p['Prix Achat']||Math.round(p['Prix Unit']*0.7),qty:qte});renderPanier();clearArticleFields();}
function clearArticleFields(){document.getElementById('codeArt').value='';document.getElementById('pvArt').value='';document.getElementById('searchArt').value='';document.getElementById('qteArt').value=1;}
function renderPanier(){ if(!PANIER.length){ document.getElementById('panierList').innerHTML='Panier vide'; document.getElementById('totalPanier').innerText='0 FC'; document.getElementById('totalFinal').innerText='0 FC'; document.getElementById('remiseInfo').innerText=''; document.getElementById('remiseInfoFC').innerText=''; return; } let {brut,remisePct,remiseVal,final}=getTotals(); document.getElementById('panierList').innerHTML=PANIER.map((it,i)=>`<div class="panierItem"><span>${it.CODE} ${it.Designation} x${it.qty}</span><span>${(it.qty*it.Prix).toLocaleString()} FC <button onclick="PANIER.splice(${i},1);renderPanier()" style="background:red;color:#fff;border:none;border-radius:4px">X</button></span></div>`).join(''); document.getElementById('totalPanier').innerText=brut.toLocaleString()+' FC'; if(remisePct>0){ document.getElementById('remiseInfo').innerText=`Remise ${remisePct}%`; document.getElementById('remiseInfoFC').innerText=`- ${remiseVal.toLocaleString()} FC`; } else { document.getElementById('remiseInfo').innerText='Pas de remise'; document.getElementById('remiseInfoFC').innerText=''; } document.getElementById('totalFinal').innerText=final.toLocaleString()+' FC à payer'; }
async function validerVente(){
 if(BLOCKED_PINS_CACHE.includes(CURRENT_VENDEUR?.pin)){ alert('🚫 Compte bloqué'); logoutAll(); return; }
 if(!PANIER.length) return alert('Panier vide');
 let {brut,remisePct,remiseVal,final}=getTotals();
 let benef=PANIER.reduce((s,i)=>s+i.qty*(i.Prix-(i.PA||0)),0)-remiseVal;
 let clientNom=document.getElementById('clientNom').value||'Comptoir';
 let clientTel=document.getElementById('clientTel').value||'';
 let payMode=document.getElementById('payMode').value;
 let montantPaye=parseFloat(document.getElementById('montantPaye').value)||final;
 if(FIREBASE_CONNECTED){ for(let it of PANIER){ let snap=await db.ref('shops/'+SHOP+'/stock/'+it.CODE+'/Quantite').once('value'); let stockActuel=snap.val(); if(stockActuel===null){ alert(`❌ Article ${it.CODE} n'existe plus`); return; } if(stockActuel < it.qty){ alert(`❌ STOCK INSUFFISANT pour ${it.CODE}\nStock: ${stockActuel} | Demandé: ${it.qty}`); return; } } }
 let id=Date.now();
 let vente={date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'inconnu',vendeurNom:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'inconnu',vendeurPin:CURRENT_VENDEUR?CURRENT_VENDEUR.pin:'',client:{nom:clientNom,tel:clientTel},items:PANIER,totalBrut:brut,remisePct:remisePct,remiseVal:remiseVal,total:final,benefice:benef,payement:payMode,montantPaye:montantPaye,reste:final-montantPaye, offline:!FIREBASE_CONNECTED};
 if(!FIREBASE_CONNECTED){
   let stockUpdates=[]; PANIER.forEach(it=>{ let st=STOCK.find(s=>s.CODE===it.CODE); if(st){ stockUpdates.push({CODE:it.CODE,newQte:st.Quantite-it.qty}); st.Quantite-=it.qty; } });
   OFFLINE_QUEUE.push({type:'vente',shop:SHOP,id:id,data:vente,stockUpdates:stockUpdates}); saveQueue(); saveStockCache(); VENTES.push(vente);
   PANIER=[];renderPanier();clearArticleFields();document.getElementById('clientNom').value='';document.getElementById('clientTel').value='';document.getElementById('montantPaye').value='';document.getElementById('remise').value=0; renderVentesJour(); renderStock(); updateKPI(); updateOfflineUI();
   alert('✅ Vente OFFLINE (12h max): '+final.toLocaleString()+' FC'); return;
 }
 try{
   for(let it of PANIER){ let ref=db.ref('shops/'+SHOP+'/stock/'+it.CODE+'/Quantite'); let result=await ref.transaction(currentQte=>{ if(currentQte===null) return; if(currentQte < it.qty) return; return currentQte - it.qty; }); if(!result.committed){ alert(`❌ VENTE ANNULEE - Stock insuffisant pour ${it.CODE}`); for(let prev of PANIER){ if(prev===it) break; await db.ref('shops/'+SHOP+'/stock/'+prev.CODE+'/Quantite').transaction(q=>{ return (q||0)+prev.qty; }); } return; } let st=STOCK.find(s=>s.CODE===it.CODE); if(st) st.Quantite=result.snapshot.val(); }
   await db.ref('shops/'+SHOP+'/ventes/'+id).set(vente); saveStockCache(); logPresence('VENTE', vente.total+' FC'); alert('✅ Vente SECURISEE: '+final.toLocaleString()+' FC');
 }catch(e){ alert('❌ Erreur vente: '+e.message); return; }
 PANIER=[];renderPanier();clearArticleFields();document.getElementById('clientNom').value='';document.getElementById('clientTel').value='';document.getElementById('montantPaye').value='';document.getElementById('remise').value=0; renderVentesJour(); renderStock(); updateKPI(); updateOfflineUI();
}
function renderVentesJour(){ let today=new Date().toDateString(); let vToday=VENTES.filter(v=>new Date(v.date).toDateString()===today).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,20); let vQueue=OFFLINE_QUEUE.filter(q=>q.type==='vente').map(q=>q.data).filter(v=>new Date(v.date).toDateString()===today); let all=[...vToday,...vQueue].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,20); document.getElementById('ventesJour').innerHTML=all.map(v=>{ let syncLabel=v.offline? '<span style="background:#ef4444;color:#fff;padding:2px 6px;border-radius:10px">OFFLINE</span>' : '<span style="background:#22c55e;color:#000;padding:2px 6px;border-radius:10px">SYNC</span>'; return `<tr><td>${new Date(v.date).toLocaleTimeString()}</td><td>${v.vendeurNom||v.vendeur||'?'}</td><td>${v.client?.nom||''}</td><td>${(v.items||[]).map(i=>i.CODE+' x'+i.qty).join(', ')}</td><td>${(v.total||0).toLocaleString()}</td><td>${syncLabel}</td></tr>`; }).join('')||'<tr><td colspan=6>Aucune vente</td></tr>'; }
function renderStock(){let q=(document.getElementById('searchS').value||'').toLowerCase();let f=STOCK.filter(p=>p.actif!==false).filter(p=>(p.CODE||'').toLowerCase().includes(q)||(p.Designation||'').toLowerCase().includes(q)).sort((a,b)=>(a.CODE||'').localeCompare(b.CODE||''));document.getElementById('stockT').innerHTML=f.map(p=>{let actif=p.actif!==false;let statut=p.Quantite<= (p.seuil||3)?`<span style="color:red;font-weight:bold">⚠️ Faible</span>`:`<span style="color:green">OK</span>`;return `<tr style="${!actif?'background:#fee;opacity:0.6':''}"><td>${p.CODE}</td><td>${p.Designation}</td><td>${p.Quantite}</td><td>${p['Prix Unit']?.toLocaleString()}</td><td>${statut}</td><td>${actif?'✅ Actif':'🚫 Désactivé'}</td></tr>`;}).join('');}
function renderCaisse(){ let today=new Date().toDateString(); let vToday=VENTES.filter(v=>new Date(v.date).toDateString()===today); let vQueue=OFFLINE_QUEUE.filter(q=>q.type==='vente').map(q=>q.data).filter(v=>new Date(v.date).toDateString()===today); let allV=[...vToday,...vQueue]; let ca=allV.reduce((s,v)=>s+(v.total||0),0); let depJ=DEP.filter(d=>new Date(d.date).toDateString()===today).reduce((s,d)=>s+(d.montant||0),0); let versJ=VERS.filter(v=>new Date(v.date).toDateString()===today).reduce((s,v)=>s+(v.montant||0),0); document.getElementById('caJour').innerText='CA: '+ca.toLocaleString(); document.getElementById('caJour2').innerText=ca.toLocaleString()+' FC'; document.getElementById('aVerser').innerText=(ca-depJ-versJ).toLocaleString()+' FC'; let caTotal=VENTES.reduce((s,v)=>s+(v.total||0),0)+OFFLINE_QUEUE.filter(q=>q.type==='vente').reduce((s,q)=>s+(q.data.total||0),0); let depTotal=DEP.reduce((s,d)=>s+(d.montant||0),0); let versTotal=VERS.reduce((s,v)=>s+(v.montant||0),0); let cumule = caTotal - depTotal - versTotal; let allDates = [...VENTES.map(v=>new Date(v.date)),...DEP.map(d=>new Date(d.date)),...VERS.map(v=>new Date(v.date))].filter(d=>!isNaN(d.getTime())); let dateDebut = allDates.length? new Date(Math.min(...allDates)) : new Date(); let dateFin = new Date(); let fmt = d => d.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}); let fmtH = d => d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}); let el=document.getElementById('aVerserCumule'); if(el){ el.innerText=cumule.toLocaleString()+' FC'; el.style.color=cumule>0?'#ef4444':'#16a34a'; } let elD=document.getElementById('cumuleDates'); if(elD){ elD.innerText=`Du ${fmt(dateDebut)} ${fmtH(dateDebut)} jusqu'au ${fmt(dateFin)} ${fmtH(dateFin)}`; } let all=[...allV.map(v=>({date:v.date,type:'Vente',montant:v.total,motif:(v.items||[]).map(i=>i.CODE).join(',')})),...DEP.filter(d=>new Date(d.date).toDateString()===today).map(d=>({date:d.date,type:'Dépense',montant:-d.montant,motif:d.motif})),...VERS.filter(v=>new Date(v.date).toDateString()===today).map(v=>({date:v.date,type:'Versement',montant:-v.montant,motif:v.description}))].sort((a,b)=>new Date(b.date)-new Date(a.date)); document.getElementById('caisseList').innerHTML=all.map(a=>`<tr><td>${new Date(a.date).toLocaleTimeString()}</td><td>${a.type}</td><td style="color:${a.montant<0?'red':'green'}">${a.montant.toLocaleString()}</td><td>${a.motif}</td></tr>`).join('');}
function updateKPI(){renderCaisse();}
function addDepense(){ let motif=document.getElementById('motifDep').value;let mont=parseFloat(document.getElementById('montDep').value);if(!mont)return alert('Montant');let desc=document.getElementById('descDep').value; let id=Date.now(); let data={date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',motif:motif,montant:mont,description:desc, offline:!FIREBASE_CONNECTED}; if(FIREBASE_CONNECTED){ db.ref('shops/'+SHOP+'/depenses/'+id).set(data); } else { OFFLINE_QUEUE.push({type:'depense',shop:SHOP,id:id,data:data}); saveQueue(); DEP.push(data); renderCaisse(); updateOfflineUI(); } document.getElementById('montDep').value='';document.getElementById('descDep').value='';}
function addVersement(){ let mont=parseFloat(document.getElementById('montVers').value);if(!mont)return alert('Montant');let desc=document.getElementById('descVers').value; let id=Date.now(); let data={date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',montant:mont,description:desc, offline:!FIREBASE_CONNECTED}; if(FIREBASE_CONNECTED){ db.ref('shops/'+SHOP+'/versements/'+id).set(data); } else { OFFLINE_QUEUE.push({type:'versement',shop:SHOP,id:id,data:data}); saveQueue(); VERS.push(data); renderCaisse(); updateOfflineUI(); } document.getElementById('montVers').value='';document.getElementById('descVers').value='';}
function openEntree(){ let code=prompt('CODE article entrée?'); if(!code) return; code=code.toUpperCase().trim(); let st=STOCK.find(s=>s.CODE===code); if(!st) return alert('CODE introuvable'); let qty=parseInt(prompt(`Qté entrée pour ${st.Designation} (stock actuel ${st.Quantite})?`)); if(!qty||qty<=0) return; let qui = CURRENT_VENDEUR? CURRENT_VENDEUR.nom : (localStorage.getItem('vendeur_nom')||''); let pin = CURRENT_VENDEUR? CURRENT_VENDEUR.pin : (localStorage.getItem('vendeur_pin')||''); let now = new Date(); let id=Date.now(); let newQte=st.Quantite+qty; st.Quantite=newQte; saveStockCache(); renderStock(); let ent={ date: now.toISOString(), jour: now.toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}), heure: now.toLocaleTimeString('fr-FR'), CODE: code, Designation: st.Designation, boutique: SHOP, qty: qty, vendeur: qui, faitPar: qui, pin: pin, vendeurPin: pin }; if(FIREBASE_CONNECTED){ db.ref('shops/'+SHOP+'/stock/'+code).update({Quantite:newQte}); db.ref('shops/'+SHOP+'/entrees/'+id).set(ent); } else { OFFLINE_QUEUE.push({type:'entree',shop:SHOP,id:id,CODE:code,newQte:newQte,data:ent}); saveQueue(); } alert('✅ Entrée +'+qty+' '+code); }
function genSyntheseVendeur(){let du=new Date(document.getElementById('du').value);let au=new Date(document.getElementById('au').value);au.setHours(23,59,59);let vPeriode=VENTES.filter(v=>{let d=new Date(v.date);return d>=du&&d<=au;});let byArt={};vPeriode.forEach(v=>{(v.items||[]).forEach(i=>{if(!byArt[i.CODE])byArt[i.CODE]={CODE:i.CODE,Designation:i.Designation||STOCK.find(s=>s.CODE===i.CODE)?.Designation||i.CODE,qty:0,ca:0};byArt[i.CODE].qty+=i.qty;byArt[i.CODE].ca+=i.qty*i.Prix;});});let totalQte=Object.values(byArt).reduce((s,a)=>s+a.qty,0);let totalCA=Object.values(byArt).reduce((s,a)=>s+a.ca,0);let html=`<h4>Synthèse ${SHOP} - ${du.toLocaleDateString()} au ${au.toLocaleDateString()} - Vendeur: ${CURRENT_VENDEUR?CURRENT_VENDEUR.nom:''}</h4><p>Total: <b>${totalQte}</b> - CA: <b>${totalCA.toLocaleString()} FC</b></p><table><tr><th>CODE</th><th>Désignation</th><th>Qté</th><th>CA</th><th>Stock</th></tr>`+Object.values(byArt).sort((a,b)=>b.qty-a.qty).map(r=>`<tr><td>${r.CODE}</td><td>${r.Designation}</td><td>${r.qty}</td><td>${r.ca.toLocaleString()} FC</td><td>${STOCK.find(s=>s.CODE===r.CODE)?.Quantite??''}</td></tr>`).join('')+'</table>';document.getElementById('syntheseC').innerHTML=html;}
function pdfSynthese(){let c=document.getElementById('syntheseC').innerHTML;let w=window.open('','','width=900,height=900');w.document.write('<html><head><style>table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:6px}th{background:#111;color:#fff}</style></head><body>'+c+'</body></html>');w.document.close();w.print();}
function autoFillTaux(){let t=CONFIG_ENT.taux||{};let tauxUSD=t.USD||CONFIG_ENT.tauxUSD||0;if(tauxUSD){if(!document.getElementById('tauxDevis').value) document.getElementById('tauxDevis').value=tauxUSD;if(!document.getElementById('tauxFact').value) document.getElementById('tauxFact').value=tauxUSD;}}
function getTaux(devise){let td=parseFloat(document.getElementById('tauxDevis')?.value)||0;let tf=parseFloat(document.getElementById('tauxFact')?.value)||0;let tConf=CONFIG_ENT.taux||{};let inputTaux = td||tf||0;if(devise==='FC') return 1;if(tConf[devise]) return inputTaux||tConf[devise];if(devise==='USD') return inputTaux||tConf.USD||CONFIG_ENT.tauxUSD||0;if(devise==='EUR') return inputTaux||tConf.EUR||CONFIG_ENT.tauxEUR||0;return inputTaux||0;}
function convertFCtoDevise(montantFC,devise){let t=getTaux(devise);if(!t||devise==='FC'||devise===(CONFIG_ENT.deviseBase||'FC')) return montantFC;return montantFC/t;}
function onDeviseDevisChange(){let d=document.getElementById('deviseDevis').value;let tConf=CONFIG_ENT.taux||{};if(tConf[d]) document.getElementById('tauxDevis').value=tConf[d];else if(d==='USD'&&CONFIG_ENT.tauxUSD) document.getElementById('tauxDevis').value=CONFIG_ENT.tauxUSD;else if(d!=='FC') document.getElementById('tauxDevis').value='';renderPanierDevis();}
function onDeviseFactChange(){let d=document.getElementById('deviseFact').value;let tConf=CONFIG_ENT.taux||{};if(tConf[d]) document.getElementById('tauxFact').value=tConf[d];else if(d==='USD'&&CONFIG_ENT.tauxUSD) document.getElementById('tauxFact').value=CONFIG_ENT.tauxUSD;else if(d!=='FC') document.getElementById('tauxFact').value='';renderPanierFact();}
function searchArticleDevis(){let q=document.getElementById('searchArtDevis').value.toLowerCase().trim();let sug=document.getElementById('suggestDevis');if(!q){sug.style.display='none';return;}let f=STOCK.filter(p=>p.actif!==false).filter(p=>(p.CODE||'').toLowerCase().includes(q)||(p.Designation||'').toLowerCase().includes(q)).slice(0,10);sug.innerHTML=f.map(p=>`<div onclick="selectArtDevis('${p.CODE}')"><b>${p.CODE}</b> - ${p.Designation} - ${p['Prix Unit']?.toLocaleString()} FC - Stock:${p.Quantite}</div>`).join('');sug.style.display='block';}
function searchArticleFact(){let q=document.getElementById('searchArtFact').value.toLowerCase().trim();let sug=document.getElementById('suggestFact');if(!q){sug.style.display='none';return;}let f=STOCK.filter(p=>p.actif!==false).filter(p=>(p.CODE||'').toLowerCase().includes(q)||(p.Designation||'').toLowerCase().includes(q)).slice(0,10);sug.innerHTML=f.map(p=>`<div onclick="selectArtFact('${p.CODE}')"><b>${p.CODE}</b> - ${p.Designation} - ${p['Prix Unit']?.toLocaleString()} FC - Stock:${p.Quantite}</div>`).join('');sug.style.display='block';}
function selectArtDevis(code){let p=STOCK.find(x=>x.CODE===code);if(!p)return;document.getElementById('codeArtDevis').value=p.CODE;document.getElementById('pvArtDevis').value=p['Prix Unit'];document.getElementById('searchArtDevis').value=p.CODE+' '+p.Designation;document.getElementById('suggestDevis').style.display='none';document.getElementById('qteArtDevis').focus();}
function selectArtFact(code){let p=STOCK.find(x=>x.CODE===code);if(!p)return;document.getElementById('codeArtFact').value=p.CODE;document.getElementById('pvArtFact').value=p['Prix Unit'];document.getElementById('searchArtFact').value=p.CODE+' '+p.Designation;document.getElementById('suggestFact').style.display='none';document.getElementById('qteArtFact').focus();}
function addPanierDevis(){let code=document.getElementById('codeArtDevis').value;if(!code)return alert('Choisis');let p=STOCK.find(x=>x.CODE===code);let qte=parseInt(document.getElementById('qteArtDevis').value)||1;if(qte>p.Quantite)return alert('Stock '+p.Quantite);let ex=PANIER_DEVIS.find(x=>x.CODE===code);if(ex)ex.qty+=qte;else PANIER_DEVIS.push({CODE:p.CODE,Designation:p.Designation,Prix:p['Prix Unit'],qty:qte});document.getElementById('codeArtDevis').value='';document.getElementById('pvArtDevis').value='';document.getElementById('searchArtDevis').value='';document.getElementById('qteArtDevis').value=1;document.getElementById('suggestDevis').style.display='none';renderPanierDevis();}
function addPanierFact(){let code=document.getElementById('codeArtFact').value;if(!code)return alert('Choisis');let p=STOCK.find(x=>x.CODE===code);let qte=parseInt(document.getElementById('qteArtFact').value)||1;if(qte>p.Quantite)return alert('Stock '+p.Quantite);let ex=PANIER_FACT.find(x=>x.CODE===code);if(ex)ex.qty+=qte;else PANIER_FACT.push({CODE:p.CODE,Designation:p.Designation,Prix:p['Prix Unit'],qty:qte});document.getElementById('codeArtFact').value='';document.getElementById('pvArtFact').value='';document.getElementById('searchArtFact').value='';document.getElementById('qteArtFact').value=1;document.getElementById('suggestFact').style.display='none';renderPanierFact();}
function renderPanierDevis(){if(!PANIER_DEVIS.length){document.getElementById('panierDevis').innerHTML='Panier devis vide';document.getElementById('totalDevis').innerText='0';document.getElementById('totalDevisFC').innerText='0 FC';document.getElementById('detailDevis').innerText='';document.getElementById('convertInfoDevis').innerText='';return;}let brut=PANIER_DEVIS.reduce((s,i)=>s+i.qty*i.Prix,0);let rem=parseFloat(document.getElementById('remiseDevis').value)||0;let tvaOn=document.getElementById('tvaDevis').value==='oui';let remVal=brut*rem/100;let base=brut-remVal;let tva=tvaOn?base*0.16:0;let ttcFC=base+tva;let devise=document.getElementById('deviseDevis').value;let ttcDevise=convertFCtoDevise(ttcFC,devise);let taux=getTaux(devise);document.getElementById('panierDevis').innerHTML=PANIER_DEVIS.map((it,i)=>`<div class="panierItem"><span>${it.CODE} x${it.qty}</span><span>${(it.qty*it.Prix).toLocaleString()} FC <button onclick="PANIER_DEVIS.splice(${i},1);renderPanierDevis()" style="background:red;color:#fff;border:none">X</button></span></div>`).join('');document.getElementById('totalDevisFC').innerText=ttcFC.toLocaleString()+' FC';document.getElementById('totalDevis').innerText=devise==='FC'?ttcFC.toLocaleString()+' FC':(taux?ttcDevise.toLocaleString()+' '+devise:'Entre taux');document.getElementById('convertInfoDevis').innerText=devise!=='FC'&&taux?`Taux: 1 ${devise} = ${taux} FC`:(devise!=='FC'?'⚠️ Taux manquant':'');document.getElementById('detailDevis').innerText=`HT:${base.toLocaleString()} TVA:${tva.toLocaleString()} Remise:-${remVal.toLocaleString()}`;}
function validerDevis(){if(!PANIER_DEVIS.length)return alert('Vide');if(!document.getElementById('clientNomDevis').value)return alert('Nom client');let brut=PANIER_DEVIS.reduce((s,i)=>s+i.qty*i.Prix,0);let rem=parseFloat(document.getElementById('remiseDevis').value)||0;let tvaOn=document.getElementById('tvaDevis').value==='oui';let remVal=brut*rem/100;let base=brut-remVal;let tva=tvaOn?base*0.16:0;let ttcFC=base+tva;let devise=document.getElementById('deviseDevis').value;let taux=parseFloat(document.getElementById('tauxDevis').value)||getTaux(devise);if(devise!=='FC'&&!taux)return alert('Taux obligatoire pour '+devise);let ttcDevise=convertFCtoDevise(ttcFC,devise);let numero='DEV-'+SHOP+'-'+Date.now().toString().slice(-6);let d={numero,date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',vendeurNom:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',client:{nom:document.getElementById('clientNomDevis').value,tel:document.getElementById('clientTelDevis').value},items:PANIER_DEVIS,totalHT:base,tva,totalTTC:ttcDevise,totalTTC_FC:ttcFC,totalBrut:brut,remisePct:rem,remiseVal:remVal,baseHT:base,statut:'En attente',tvaAppliquee:tvaOn,devise,taux,config:{...CONFIG_ENT}};db.ref('shops/'+SHOP+'/devis/'+Date.now()).set(d).then(()=>{PANIER_DEVIS=[];document.getElementById('clientNomDevis').value='';renderPanierDevis();alert('Devis '+numero);});}
function renderDevisList(){document.getElementById('devisList').innerHTML=DEVIS.slice(0,30).map(d=>`<tr><td>${d.numero}</td><td>${d.client?.nom}</td><td>${(d.totalTTC||0).toLocaleString()} ${d.devise||'FC'}</td><td>${d.devise||'FC'}</td><td>${d.taux||''}</td><td><button class="btn btn-b" style="width:auto;padding:4px" onclick="convertDevisToFact('${d._id}')">→Fact</button> <button class="btn btn-y" style="width:auto;padding:4px" onclick="printDevisDoc('${d._id}')">PDF</button></td></tr>`).join('')||'<tr><td colspan=6>Aucun</td></tr>';}
function convertDevisToFact(id){let d=DEVIS.find(x=>x._id===id);if(!d)return;PANIER_FACT=d.items;document.getElementById('clientNomFact').value=d.client?.nom||'';document.getElementById('clientTelFact').value=d.client?.tel||'';document.getElementById('remiseFact').value=d.remisePct||0;document.getElementById('tvaFact').value=d.tvaAppliquee?'oui':'non';document.getElementById('deviseFact').value=d.devise||'FC';document.getElementById('tauxFact').value=d.taux||'';switchTab('facture');renderPanierFact();}
function printDoc(htmlContent){let iframe=document.createElement('iframe');iframe.style.position='fixed';iframe.style.right='0';iframe.style.bottom='0';iframe.style.width='0';iframe.style.height='0';iframe.style.border='0';document.body.appendChild(iframe);let doc=iframe.contentWindow.document;doc.open();doc.write(htmlContent);doc.close();setTimeout(()=>{iframe.contentWindow.focus();iframe.contentWindow.print();setTimeout(()=>{document.body.removeChild(iframe);},1000);},500);}
function printDevisDoc(id){let d=DEVIS.find(x=>x._id===id);if(!d)return;let cfg=d.config||CONFIG_ENT;let logo=cfg.logo?`<img src="${cfg.logo}" style="width:90px">`:'';let html=`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${d.numero}</title><style>body{font-family:Arial;font-size:13px;padding:20px}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #000;padding:8px}th{background:#1e293b;color:#fff}</style></head><body><div style="display:flex;justify-content:space-between"><div><h2>${cfg.nom}</h2>${cfg.adresse||''}<br>Tel:${cfg.tel||''}</div><div>${logo}</div></div><hr><center><h3 style="background:#0b5e2f;color:#fff;padding:8px">DEVIS ${d.numero} - ${d.devise||'FC'}</h3>Taux: ${d.taux||'1'} - Date:${new Date(d.date).toLocaleDateString('fr-FR')}</center>Client:<b>${d.client?.nom}</b><br><table><tr><th>CODE</th><th>Qté</th><th>PU FC</th><th>Total FC</th></tr>${d.items.map(it=>`<tr><td>${it.CODE}</td><td>${it.qty}</td><td>${it.Prix.toLocaleString()}</td><td>${(it.qty*it.Prix).toLocaleString()}</td></tr>`).join('')}</table><div style="text-align:right">Total FC:${(d.totalTTC_FC||0).toLocaleString()}<br><b>TTC ${d.devise||'FC'}: ${(d.totalTTC||0).toLocaleString()} ${d.devise||'FC'}</b></div></body></html>`;printDoc(html);}
function printFactDoc(id){let f=FACTURES.find(x=>x._id===id);if(!f)return;let cfg=f.config||CONFIG_ENT;let logo=cfg.logo?`<img src="${cfg.logo}" style="width:90px">`:'';let html=`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${f.numero}</title><style>body{font-family:Arial;font-size:13px;padding:20px}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{border:1px solid #000;padding:8px}th{background:#1e293b;color:#fff}</style></head><body><div style="display:flex;justify-content:space-between"><div><h2>${cfg.nom}</h2>${cfg.adresse||''}<br>Tel:${cfg.tel||''}</div><div>${logo}</div></div><hr><center><h3 style="background:#0b5e2f;color:#fff;padding:8px">FACTURE ${f.numero} - ${f.devise||'FC'}</h3>Taux: ${f.taux||'1'}</center>Client:<b>${f.client?.nom}</b><br><table><tr><th>CODE</th><th>Qté</th><th>PU FC</th><th>Total FC</th></tr>${f.items.map(it=>`<tr><td>${it.CODE}</td><td>${it.qty}</td><td>${it.Prix.toLocaleString()}</td><td>${(it.qty*it.Prix).toLocaleString()}</td></tr>`).join('')}</table><div style="text-align:right">Total FC:${(f.totalTTC_FC||0).toLocaleString()}<br><b>TTC ${f.devise||'FC'}: ${(f.totalTTC||0).toLocaleString()} ${f.devise||'FC'}</b></div></body></html>`;printDoc(html);}
function renderPanierFact(){if(!PANIER_FACT.length){document.getElementById('panierFact').innerHTML='Panier facture vide';document.getElementById('htFact').innerText='0';document.getElementById('tvaValFact').innerText='0';document.getElementById('totalFact').innerText='0';document.getElementById('convertInfoFact').innerText='';return;}let brut=PANIER_FACT.reduce((s,i)=>s+i.qty*i.Prix,0);let rem=parseFloat(document.getElementById('remiseFact').value)||0;let tvaOn=document.getElementById('tvaFact').value==='oui';let remVal=brut*rem/100;let base=brut-remVal;let tva=tvaOn?base*0.16:0;let ttcFC=base+tva;let devise=document.getElementById('deviseFact').value;let ttcDevise=convertFCtoDevise(ttcFC,devise);let taux=getTaux(devise);document.getElementById('panierFact').innerHTML=PANIER_FACT.map((it,i)=>`<div class="panierItem"><span>${it.CODE} x${it.qty}</span><span>${(it.qty*it.Prix).toLocaleString()} FC <button onclick="PANIER_FACT.splice(${i},1);renderPanierFact()" style="background:red;color:#fff;border:none">X</button></span></div>`).join('');document.getElementById('htFact').innerText=base.toLocaleString();document.getElementById('tvaValFact').innerText=tva.toLocaleString();document.getElementById('totalFact').innerText=devise==='FC'?ttcFC.toLocaleString()+' FC':(taux?ttcDevise.toLocaleString()+' '+devise:'Entre taux');document.getElementById('convertInfoFact').innerText=devise!=='FC'&&taux?`Taux: 1 ${devise} = ${taux} FC | FC: ${ttcFC.toLocaleString()}`:(devise!=='FC'?'⚠️ Taux manquant':'');}
async function validerFacture(){
 if(!PANIER_FACT.length) return alert('Vide');
 if(!document.getElementById('clientNomFact').value) return alert('Nom client');
 let brut=PANIER_FACT.reduce((s,i)=>s+i.qty*i.Prix,0);
 let rem=parseFloat(document.getElementById('remiseFact').value)||0;
 let tvaOn=document.getElementById('tvaFact').value==='oui';
 let remVal=brut*rem/100;let base=brut-remVal;let tva=tvaOn?base*0.16:0;let ttcFC=base+tva;
 let devise=document.getElementById('deviseFact').value;let taux=parseFloat(document.getElementById('tauxFact').value)||getTaux(devise);
 if(devise!=='FC'&&!taux) return alert('Taux obligatoire');
 let ttcDevise=convertFCtoDevise(ttcFC,devise);
 if(FIREBASE_CONNECTED){
   for(let it of PANIER_FACT){
     let snap=await db.ref('shops/'+SHOP+'/stock/'+it.CODE+'/Quantite').once('value');
     if((snap.val()||0) < it.qty){ alert(`❌ STOCK INSUFFISANT ${it.CODE} Stock:${snap.val()} Demande:${it.qty}`); return; }
   }
 }
 let numero='FACT-'+SHOP+'-'+new Date().getFullYear()+'-'+(FACTURES.length+1).toString().padStart(4,'0');
 let f={numero,date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',vendeurNom:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',client:{nom:document.getElementById('clientNomFact').value,tel:document.getElementById('clientTelFact').value,rccm:document.getElementById('clientRccmFact').value},items:PANIER_FACT,totalHT:brut,remisePct:rem,remiseVal:remVal,baseHT:base,tva,totalTTC:ttcDevise,totalTTC_FC:ttcFC,totalBrut:brut,tvaAppliquee:tvaOn,devise,taux,config:{...CONFIG_ENT}};
 if(FIREBASE_CONNECTED){
   for(let it of PANIER_FACT){
     let ref=db.ref('shops/'+SHOP+'/stock/'+it.CODE+'/Quantite');
     let result=await ref.transaction(q=>{ if(q===null||q<it.qty) return; return q-it.qty; });
     if(!result.committed){ alert('❌ Facture annulée stock insuffisant '+it.CODE); return; }
     let st=STOCK.find(s=>s.CODE===it.CODE); if(st) st.Quantite=result.snapshot.val();
   }
 }
 db.ref('shops/'+SHOP+'/factures/'+Date.now()).set(f).then(()=>{
   let vente={date:new Date().toISOString(),boutique:SHOP,vendeur:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',vendeurNom:CURRENT_VENDEUR?CURRENT_VENDEUR.nom:'',vendeurPin:CURRENT_VENDEUR?CURRENT_VENDEUR.pin:'',items:PANIER_FACT,totalBrut:brut,total:ttcFC,totalDevise:ttcDevise,devise,taux,facture:numero};
   db.ref('shops/'+SHOP+'/ventes/'+Date.now()).set(vente);
   PANIER_FACT=[];renderPanierFact();alert('Facture SECURISEE '+numero);
 });
}
function renderFactList(){document.getElementById('factList').innerHTML=FACTURES.slice(0,30).map(f=>`<tr><td>${f.numero}</td><td>${f.client?.nom}</td><td>${(f.totalTTC||0).toLocaleString()} ${f.devise||'FC'}</td><td>${f.devise||'FC'}</td><td>${f.taux||''}</td><td><button class="btn btn-y" style="width:auto;padding:4px" onclick="printFactDoc('${f._id}')">PDF</button></td></tr>`).join('')||'<tr><td colspan=6>Aucune</td></tr>';}
document.getElementById('modeFact')?.addEventListener('change',e=>{let sel=document.getElementById('selectDevisFact');sel.style.display=e.target.value==='Depuis devis'?'block':'none';});
updateOfflineUI();
